replicaCount: 1

image:
  repository: depot.snc.minsi.fr/testmrq/test-mrq
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

resources:
  limits:
    cpu: "250m"
    memory: "256Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"
